# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.buttonConnect.setGeometry(QtCore.QRect(9, 9, 109, 23))
        self.buttonConnect.setObjectName("buttonConnect")
        self.buttonConnect.clicked.connect(self.connect)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 38, 131, 511))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label.setObjectName("label")
        self.boxStartT = QtWidgets.QLineEdit(self.groupBox)
        self.boxStartT.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.boxStartT.setObjectName("boxStartT")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 16, 21))
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(90, 70, 16, 21))
        self.label_12.setObjectName("label_12")
        self.boxStopT = QtWidgets.QLineEdit(self.groupBox)
        self.boxStopT.setGeometry(QtCore.QRect(10, 70, 71, 20))
        self.boxStopT.setObjectName("boxStopT")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(90, 110, 16, 21))
        self.label_14.setObjectName("label_14")
        self.boxStepT = QtWidgets.QLineEdit(self.groupBox)
        self.boxStepT.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.boxStepT.setObjectName("boxStepT")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.label_15.setObjectName("label_15")
        self.boxStartf = QtWidgets.QLineEdit(self.groupBox)
        self.boxStartf.setGeometry(QtCore.QRect(30, 160, 31, 20))
        self.boxStartf.setObjectName("boxStartf")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 160, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(70, 160, 16, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(10, 200, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(70, 200, 16, 21))
        self.label_20.setObjectName("label_20")
        self.boxStopf = QtWidgets.QLineEdit(self.groupBox)
        self.boxStopf.setGeometry(QtCore.QRect(30, 200, 31, 20))
        self.boxStopf.setObjectName("boxStopf")
        self.boxMultiplef = QtWidgets.QLineEdit(self.groupBox)
        self.boxMultiplef.setGeometry(QtCore.QRect(30, 240, 31, 20))
        self.boxMultiplef.setObjectName("boxMultiplef")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(70, 240, 16, 21))
        self.label_23.setObjectName("label_23")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 240, 16, 16))
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 220, 81, 16))
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_24.setObjectName("label_24")
        self.boxLevelV = QtWidgets.QLineEdit(self.groupBox)
        self.boxLevelV.setGeometry(QtCore.QRect(10, 290, 71, 20))
        self.boxLevelV.setObjectName("boxLevelV")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(90, 290, 16, 21))
        self.label_25.setObjectName("label_25")
        self.boxBiasV = QtWidgets.QLineEdit(self.groupBox)
        self.boxBiasV.setGeometry(QtCore.QRect(10, 330, 71, 20))
        self.boxBiasV.setObjectName("boxBiasV")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(90, 330, 16, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(10, 310, 81, 16))
        self.label_27.setObjectName("label_27")
        self.groupBoxIntegration = QtWidgets.QGroupBox(self.groupBox)
        self.groupBoxIntegration.setGeometry(QtCore.QRect(0, 360, 121, 81))
        self.groupBoxIntegration.setObjectName("groupBoxIntegration")
        self.rButtonSHORT = QtWidgets.QRadioButton(self.groupBoxIntegration)
        self.rButtonSHORT.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rButtonSHORT.setTabletTracking(False)
        self.rButtonSHORT.setAcceptDrops(False)
        self.rButtonSHORT.setAutoFillBackground(False)
        self.rButtonSHORT.setChecked(False)
        self.rButtonSHORT.setObjectName("rButtonSHORT")
        self.rButtonMEDIUM = QtWidgets.QRadioButton(self.groupBoxIntegration)
        self.rButtonMEDIUM.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.rButtonMEDIUM.setChecked(True)
        self.rButtonMEDIUM.setObjectName("rButtonMEDIUM")
        self.rButtonLONG = QtWidgets.QRadioButton(self.groupBoxIntegration)
        self.rButtonLONG.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rButtonLONG.setObjectName("rButtonLONG")
        self.buttonStart = QtWidgets.QPushButton(self.groupBox)
        self.buttonStart.setGeometry(QtCore.QRect(10, 450, 75, 23))
        self.buttonStart.setObjectName("buttonStart")
        self.buttonStart.clicked.connect(self.startTCf)
        self.buttonStop = QtWidgets.QPushButton(self.groupBox)
        self.buttonStop.setGeometry(QtCore.QRect(10, 480, 75, 23))
        self.buttonStop.setObjectName("buttonStop")
        self.groupBoxData = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxData.setGeometry(QtCore.QRect(149, 9, 791, 771))
        self.groupBoxData.setObjectName("groupBoxData")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.groupBoxData)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 20, 771, 441))
        self.openGLWidget.setObjectName("openGLWidget")
        self.tableView = QtWidgets.QTableView(self.groupBoxData)
        self.tableView.setGeometry(QtCore.QRect(10, 480, 771, 241))
        self.tableView.setObjectName("tableView")
        self.buttonSave = QtWidgets.QPushButton(self.groupBoxData)
        self.buttonSave.setGeometry(QtCore.QRect(700, 730, 75, 23))
        self.buttonSave.setObjectName("buttonSave")
        self.pushClear = QtWidgets.QPushButton(self.groupBoxData)
        self.pushClear.setGeometry(QtCore.QRect(20, 730, 75, 23))
        self.pushClear.setObjectName("pushClear")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 550, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInstrument = QtWidgets.QMenu(self.menubar)
        self.menuInstrument.setObjectName("menuInstrument")
        self.menuExperiment = QtWidgets.QMenu(self.menubar)
        self.menuExperiment.setObjectName("menuExperiment")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionTemperature_Controller = QtWidgets.QAction(MainWindow)
        self.actionTemperature_Controller.setObjectName("actionTemperature_Controller")
        self.actionLRC_Meter = QtWidgets.QAction(MainWindow)
        self.actionLRC_Meter.setObjectName("actionLRC_Meter")
        self.actionC_V_Sweep = QtWidgets.QAction(MainWindow)
        self.actionC_V_Sweep.setObjectName("actionC_V_Sweep")
        self.actionT_C_f_Sweep = QtWidgets.QAction(MainWindow)
        self.actionT_C_f_Sweep.setObjectName("actionT_C_f_Sweep")
        self.actionStorage_Path = QtWidgets.QAction(MainWindow)
        self.actionStorage_Path.setObjectName("actionStorage_Path")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionSave_Data)
        self.menuInstrument.addAction(self.actionTemperature_Controller)
        self.menuInstrument.addAction(self.actionLRC_Meter)
        self.menuExperiment.addAction(self.actionC_V_Sweep)
        self.menuExperiment.addAction(self.actionT_C_f_Sweep)
        self.menuData.addAction(self.actionStorage_Path)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInstrument.menuAction())
        self.menubar.addAction(self.menuExperiment.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonConnect.setText(_translate("MainWindow", "Connect Instruments"))
        self.groupBox.setTitle(_translate("MainWindow", "T-C-f Sweep"))
        self.label.setText(_translate("MainWindow", "Start Temperature"))
        self.boxStartT.setText(_translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "K"))
        self.label_11.setText(_translate("MainWindow", "Stop Temperature"))
        self.label_12.setText(_translate("MainWindow", "K"))
        self.boxStopT.setText(_translate("MainWindow", "325"))
        self.label_13.setText(_translate("MainWindow", "Step"))
        self.label_14.setText(_translate("MainWindow", "K"))
        self.boxStepT.setText(_translate("MainWindow", "0.4"))
        self.label_15.setText(_translate("MainWindow", "Start Frequency"))
        self.boxStartf.setText(_translate("MainWindow", "3"))
        self.label_16.setText(_translate("MainWindow", "10E"))
        self.label_17.setText(_translate("MainWindow", "Hz"))
        self.label_18.setText(_translate("MainWindow", "Stop Frequency"))
        self.label_19.setText(_translate("MainWindow", "10E"))
        self.label_20.setText(_translate("MainWindow", "Hz"))
        self.boxStopf.setText(_translate("MainWindow", "7"))
        self.boxMultiplef.setText(_translate("MainWindow", "0.5"))
        self.label_23.setText(_translate("MainWindow", "Hz"))
        self.label_22.setText(_translate("MainWindow", "10E"))
        self.label_21.setText(_translate("MainWindow", "Multiple"))
        self.label_24.setText(_translate("MainWindow", "Level"))
        self.boxLevelV.setText(_translate("MainWindow", "1.00"))
        self.label_25.setText(_translate("MainWindow", "V"))
        self.boxBiasV.setText(_translate("MainWindow", "0.000"))
        self.label_26.setText(_translate("MainWindow", "V"))
        self.label_27.setText(_translate("MainWindow", "Bias"))
        self.groupBoxIntegration.setTitle(_translate("MainWindow", "Integration"))
        self.rButtonSHORT.setText(_translate("MainWindow", "SHORT"))
        self.rButtonMEDIUM.setText(_translate("MainWindow", "MEDIUM"))
        self.rButtonLONG.setText(_translate("MainWindow", "LONG"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))
        self.groupBoxData.setTitle(_translate("MainWindow", "Data"))
        self.buttonSave.setText(_translate("MainWindow", "Save"))
        self.pushClear.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuInstrument.setTitle(_translate("MainWindow", "Instrument"))
        self.menuExperiment.setTitle(_translate("MainWindow", "Experiment"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuSetting.setTitle(_translate("MainWindow", "About"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data"))
        self.actionTemperature_Controller.setText(_translate("MainWindow", "Temperature Controller"))
        self.actionLRC_Meter.setText(_translate("MainWindow", "LRC Meter"))
        self.actionC_V_Sweep.setText(_translate("MainWindow", "C-V Sweep"))
        self.actionT_C_f_Sweep.setText(_translate("MainWindow", "T-C-f Sweep"))
        self.actionStorage_Path.setText(_translate("MainWindow", "Storage Path"))

